version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    container_name: mosquitto
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf:rw"
    ports:
      - "1883:1883"
      - "8883:8883"



